spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qz-demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 
  session: 
    store-type: none 
  application:
    name: qz_api
  jpa: 
    hibernate: 
      ddl-auto: none
    show-sql: true
server:
  port: 8081
