spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qz-demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 
  session: 
    store-type: none 
#  application:
#    name: qz_api
#  jpa: 
#    hibernate: 
#      ddl-auto: none
#    show-sql: true
server:
  port: 8082
  session: 
    timeout: 600
#security: 
#  basic: 
#    enabled: false 

qz: 
  security: 
    browser:  
#      loginPage: /demo-signIn.html
      loginType: JSON
      signUpUrl: /demo-signUp.html
      signOutUrl: /demo-logout.html
#    code: 
#      image: 
#        length: 6
#        width: 100
#        url: /user/*

    social: 
      qq: 
#        app-id:  
#        app-secret:  
        providerId: callback.do
      
      filterProcessesUrl:  /qqLogin
      weixin: 
#        app-id: 
#        app-secret: 
      
security: 
  oauth2: 
    client[0]: 
      clientId: qz
      clientSecret: qzsecret
      accessTokenValidateSeconds: 3600
    clients[1]: 
      clientId: test
      clientSecret: test
#    tokenStore: redis
      
